---
language: python

sudo: required
dist: trusty

python:
  - '3.5'

# Prepare (install dependencies, collect statics, locale)
install:
   - sudo apt-get update -qy
   - sudo apt-get install -y python-dev python-pip gettext pandoc
   - pip install coverage coveralls
   - pip install -r requirements.txt

# Start tests
script:
   - coverage run -m unittest
   - coverage report

# Generate test coverage
after_success:
  - coveralls
